name: CD Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.ref, "release")
    steps:
      - uses: actions/checkout@v1
      - name: Yarn Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Jest Tests
        run: yarn test:ci
      - name: Dist Build
        run: yarn build:dist
      - name: Lib Build
        run: yarn build:lib
      - name: Compile Styles
        run: yarn build:styles
      - name: Bump Version
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "CI"
          yarn version --patch
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Deploy Storybook
        run: yarn storybook-to-ghpages --ci
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
